version: '3.9'

services:
  db:
    container_name: db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=unicorn
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=poke

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/root/redis
    environment:
      - REDIS_PASSWORD=topsecret
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  db:
  redis:
